application: myblog
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /img
  static_dir: img

- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico

- url: /css
  static_dir: css

- url: /ckeditor
  static_dir: ckeditor

- url: /font-awesome-4.6.3
  static_dir: font-awesome-4.6.3

- url: /admin
  script: admin.app
  login: admin

- url: /admin/.*
  script: admin.app
  login: admin

- url: .*
  script: blog.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
